services:
  recipe-cards:
    image: ghcr.io/rekirky/receipe-cards:latest
    ports:
      - "2347:80"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 recipe-cards
    restart: unless-stopped
